### ISSUE TITLE
Multiple Expansion Bug

### ISSUE THREAD

**Issue by Matime** [kpey/SnapzuEnhancement#12]
It's possible to expand a snap multiple times by attempting to expand it more than once before the first element loads. When you click to collapse it only collapses one of the expanded snap elements.

Problem Step 1: (7/16/2015 9:57:02 AM) User left click in "/t/diy - Home - Google Chrome" 
![image](https://cloud.githubusercontent.com/assets/13367437/8726675/59fa562e-2ba1-11e5-8248-34943618e4f7.png)

Problem Step 3: (7/16/2015 9:57:03 AM) User left click in "/t/diy - Home - Google Chrome" 
![image](https://cloud.githubusercontent.com/assets/13367437/8726687/67e033e4-2ba1-11e5-83ce-df62f36b2d4a.png)

Problem Step 4: (7/16/2015 9:57:09 AM) User left click in "/t/diy - Home - Google Chrome" 
![image](https://cloud.githubusercontent.com/assets/13367437/8726696/6f1579d0-2ba1-11e5-831f-831e1652d3ad.png)

Problem Step 5: (7/16/2015 9:57:11 AM) User left click in "/t/diy - Home - Google Chrome" 
![image](https://cloud.githubusercontent.com/assets/13367437/8726701/73300ecc-2ba1-11e5-8e28-233303b62716.png)

Problem Step 6: (7/16/2015 9:57:13 AM) User left click in "/t/diy - Home - Google Chrome" 
![image](https://cloud.githubusercontent.com/assets/13367437/8726704/778db38e-2ba1-11e5-9687-481d4aadc025.png)

This seems to only occur when browsing a tribe and not the front page.

**Comment by kpey** [comment]
This appears to be fixed in the latest version.
