### ISSUE TITLE
Visual bug with list module

### ISSUE THREAD

**Issue by logomaster256** [kpey/SnapzuEnhancement#18]
#### To reproduce
 * Go to http://snapzu.com/t/enhancement/
 * Expando the first one

#### Images
What it looks like
![2015-07-19--1437335323_1177x676_scrot](https://cloud.githubusercontent.com/assets/3049847/8767522/147dab34-2e60-11e5-9557-4ac46fe5c4ee.png)
![2015-07-19--1437335357_1175x686_scrot](https://cloud.githubusercontent.com/assets/3049847/8767523/1487080a-2e60-11e5-9f69-02da15e66e47.png)
What it should look like
![2015-07-19--1437335803_1157x636_scrot](https://cloud.githubusercontent.com/assets/3049847/8767579/28a2a47e-2e61-11e5-8a4e-8dbb97eb993e.png)
![2015-07-19--1437335552_1157x524_scrot](https://cloud.githubusercontent.com/assets/3049847/8767540/8d82cd66-2e60-11e5-88c8-0aaf777d5778.png)

**Comment by kpey** [comment]
Fix introduced a bug with short text posts
